In [3]:
import pandas as pd
df = pd.read_csv('india_ecommerce_customers.csv')
df.head()

,customer_id,name,age,gender,state,city,segment,registration_date
0,CUST05109,Diya Nair,45.0,MALE,Gujarat,Gandhinagar,Luxury,07-Feb-2020
1,CUST00782,KABIR MENON,39.0,female,Uttar Pradesh,Agra,Premium,2021-08-02
2,CUST01577,Lakshmi Sharma,45.0,F,maharashtra,Pune,Mid-Range,20-Dec-2020
3,CUST04580,sanjay singh,59.0,female,WEST BENGAL,Kolkata,Budget,15/09/2021
4,CUST04492,Aditya Mehta,59.0,M,Rajasthan,Jaipur,Budget,22-Jun-2020

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7760 entries, 0 to 7759
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        7760 non-null   object
 1   name               7760 non-null   object
 2   age                7760 non-null   float64
 3   gender             7760 non-null   object
 4   state              7760 non-null   object
 5   city               7760 non-null   object
 6   segment            7760 non-null   object
 7   registration_date  7760 non-null   object
dtypes: float64(1), object(7)
memory usage: 485.1+ KB

In [5]:
df.isnull().sum()

customer_id          0
name                 0
age                  0
gender               0
state                0
city                 0
segment              0
registration_date    0
dtype: int64

In [6]:
df['registration_date'] = pd.to_datetime(df['registration_date'],format = 'mixed')
df['registration_date'] = df['registration_date'].dt.strftime('%d-%m-%Y')
df.head()

,customer_id,name,age,gender,state,city,segment,registration_date
0,CUST05109,Diya Nair,45.0,MALE,Gujarat,Gandhinagar,Luxury,07-02-2020
1,CUST00782,KABIR MENON,39.0,female,Uttar Pradesh,Agra,Premium,02-08-2021
2,CUST01577,Lakshmi Sharma,45.0,F,maharashtra,Pune,Mid-Range,20-12-2020
3,CUST04580,sanjay singh,59.0,female,WEST BENGAL,Kolkata,Budget,15-09-2021
4,CUST04492,Aditya Mehta,59.0,M,Rajasthan,Jaipur,Budget,22-06-2020

In [7]:
df.duplicated().sum()

np.int64(23)

In [8]:
df.drop_duplicates()

,customer_id,name,age,gender,state,city,segment,registration_date
0,CUST05109,Diya Nair,45.0,MALE,Gujarat,Gandhinagar,Luxury,07-02-2020
1,CUST00782,KABIR MENON,39.0,female,Uttar Pradesh,Agra,Premium,02-08-2021
2,CUST01577,Lakshmi Sharma,45.0,F,maharashtra,Pune,Mid-Range,20-12-2020
3,CUST04580,sanjay singh,59.0,female,WEST BENGAL,Kolkata,Budget,15-09-2021
4,CUST04492,Aditya Mehta,59.0,M,Rajasthan,Jaipur,Budget,22-06-2020
...,...,...,...,...,...,...,...,...
7755,CUST07496,Aanya Joshi,19.0,M,maharashtra,pune,Premium,16-10-2021
7756,CUST05914,Riya Malhotra,45.0,male,Tamil Nadu,Salem,Premium,17-09-2020
7757,CUST05356,Diya Reddy,51.0,female,Tamil Nadu,Salem,Mid-Range,25-06-2021
7758,CUST04763,Diya Shah,61.0,Male,Gujarat,Rajkot,mid-range,07-04-2020
7759,CUST05579,Riya Pillai,22.0,M,Madhya Pradesh,Ujjain,Luxury,05-07-2020

In [9]:
columns_strip = df[['name','gender','state','city','segment']]

for col in columns_strip:
    df[col]=df[col].astype(str).str.strip().str.title()
df.head()

,customer_id,name,age,gender,state,city,segment,registration_date
0,CUST05109,Diya Nair,45.0,Male,Gujarat,Gandhinagar,Luxury,07-02-2020
1,CUST00782,Kabir Menon,39.0,Female,Uttar Pradesh,Agra,Premium,02-08-2021
2,CUST01577,Lakshmi Sharma,45.0,F,Maharashtra,Pune,Mid-Range,20-12-2020
3,CUST04580,Sanjay Singh,59.0,Female,West Bengal,Kolkata,Budget,15-09-2021
4,CUST04492,Aditya Mehta,59.0,M,Rajasthan,Jaipur,Budget,22-06-2020

In [10]:
df['age'] = df['age'].astype(int)
df.head()

,customer_id,name,age,gender,state,city,segment,registration_date
0,CUST05109,Diya Nair,45,Male,Gujarat,Gandhinagar,Luxury,07-02-2020
1,CUST00782,Kabir Menon,39,Female,Uttar Pradesh,Agra,Premium,02-08-2021
2,CUST01577,Lakshmi Sharma,45,F,Maharashtra,Pune,Mid-Range,20-12-2020
3,CUST04580,Sanjay Singh,59,Female,West Bengal,Kolkata,Budget,15-09-2021
4,CUST04492,Aditya Mehta,59,M,Rajasthan,Jaipur,Budget,22-06-2020

In [11]:
gender_replace={
    'M':'Male',
    'F':'Female'
}

df['gender'] = df['gender'].replace(gender_replace)
df.head()

,customer_id,name,age,gender,state,city,segment,registration_date
0,CUST05109,Diya Nair,45,Male,Gujarat,Gandhinagar,Luxury,07-02-2020
1,CUST00782,Kabir Menon,39,Female,Uttar Pradesh,Agra,Premium,02-08-2021
2,CUST01577,Lakshmi Sharma,45,Female,Maharashtra,Pune,Mid-Range,20-12-2020
3,CUST04580,Sanjay Singh,59,Female,West Bengal,Kolkata,Budget,15-09-2021
4,CUST04492,Aditya Mehta,59,Male,Rajasthan,Jaipur,Budget,22-06-2020

In [12]:
from sqlalchemy import create_engine


username = "root"
password = "1234"
host = "localhost"
port = "3306"
database = "india_ecomm_sales"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

table_name = "customer" 
df.to_sql(table_name, engine, if_exists="replace", index=False)

pd.read_sql("SELECT * FROM customer LIMIT 5;", engine)

,customer_id,name,age,gender,state,city,segment,registration_date
0,CUST05109,Diya Nair,45,Male,Gujarat,Gandhinagar,Luxury,07-02-2020
1,CUST00782,Kabir Menon,39,Female,Uttar Pradesh,Agra,Premium,02-08-2021
2,CUST01577,Lakshmi Sharma,45,Female,Maharashtra,Pune,Mid-Range,20-12-2020
3,CUST04580,Sanjay Singh,59,Female,West Bengal,Kolkata,Budget,15-09-2021
4,CUST04492,Aditya Mehta,59,Male,Rajasthan,Jaipur,Budget,22-06-2020