In [1]:
import pandas as pd
pd.set_option('display.max_column',None)
df = pd.read_csv("india_ecommerce_orders.csv")
df.head()

,order_id,customer_id,order_date,order_year,order_month,order_quarter,delivery_date,delivery_days,category,product,platform,payment_method,quantity,unit_price,discount_pct,discount_amount,gmv,revenue,cogs,profit,margin_pct,returned,rating,state,city,customer_segment
0,ORD658635,CUST03049,2023-06-03,2023,6,Q2,08-Jun-2023,5,Electronics,tablet,JioMart,UPI,2,56143.48,6.7%,7523.23,112286.96,"104,763.73",96277.87,8485.86,0.081,No,3.3,Tamil Nadu,chennai,mid-range
1,ORD766038,CUST04659,2023-11-10,2023,11,Q4,2023-11-13,3,Electronics,speaker,Amazon India,EMI,1,50953.37,29.6%,15082.20,50953.37,"35,871.17",32391.67,3479.50,0.097,0,4.5,DELHI,new delhi,Mid-Range
2,ORD419250,CUST02676,2023/07/19,2023,7,Q3,2023-07-24,5,fashion,Lehenga,JIOMART,credit_card,1,7456.29,0.047,350.45,7456.29,"7,105.84",4505.10,2600.74,0.366,0,4.2,KARNATAKA,Mangalore,premium
3,ORD494773,CUST06352,30-Jan-2023,2023,1,Q1,03-Feb-2023,4,Sports & Fitness,Dumbbell Set,Amazon India,UPI,1,9372.67,21.0%,1968.26,9372.67,"7,404.41",5123.85,2280.56,0.308,0,3.7,Uttar Pradesh,Kanpur,Mid-Range
4,ORD261726,CUST03540,17-Dec-2023,2023,12,Q4,20/12/2023,3,Beauty & Personal Care,Hair Oil,Meesho,UPI,2,1762.47,4.4%,155.10,3524.94,"3,369.84",1644.48,1725.36,0.512,No,4.9,Maharashtra,Mumbai,mid-range

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48301 entries, 0 to 48300
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          48301 non-null  object
 1   customer_id       48301 non-null  object
 2   order_date        48301 non-null  object
 3   order_year        48301 non-null  int64
 4   order_month       48301 non-null  int64
 5   order_quarter     48301 non-null  object
 6   delivery_date     48301 non-null  object
 7   delivery_days     48301 non-null  int64
 8   category          48301 non-null  object
 9   product           48301 non-null  object
 10  platform          48301 non-null  object
 11  payment_method    48301 non-null  object
 12  quantity          48301 non-null  int64
 13  unit_price        48301 non-null  float64
 14  discount_pct      48301 non-null  object
 15  discount_amount   48301 non-null  float64
 16  gmv               48301 non-null  float64
 17  revenue           48301 non-null  object
 18  cogs              48301 non-null  float64
 19  profit            48301 non-null  float64
 20  margin_pct        48301 non-null  float64
 21  returned          48301 non-null  object
 22  rating            48301 non-null  float64
 23  state             48301 non-null  object
 24  city              48301 non-null  object
 25  customer_segment  48301 non-null  object
dtypes: float64(7), int64(4), object(15)
memory usage: 9.6+ MB

In [3]:
df.duplicated().sum()

np.int64(57)

In [4]:
df.drop_duplicates()

,order_id,customer_id,order_date,order_year,order_month,order_quarter,delivery_date,delivery_days,category,product,platform,payment_method,quantity,unit_price,discount_pct,discount_amount,gmv,revenue,cogs,profit,margin_pct,returned,rating,state,city,customer_segment
0,ORD658635,CUST03049,2023-06-03,2023,6,Q2,08-Jun-2023,5,Electronics,tablet,JioMart,UPI,2,56143.48,6.7%,7523.23,112286.96,"104,763.73",96277.87,8485.86,0.081,No,3.3,Tamil Nadu,chennai,mid-range
1,ORD766038,CUST04659,2023-11-10,2023,11,Q4,2023-11-13,3,Electronics,speaker,Amazon India,EMI,1,50953.37,29.6%,15082.20,50953.37,"35,871.17",32391.67,3479.50,0.097,0,4.5,DELHI,new delhi,Mid-Range
2,ORD419250,CUST02676,2023/07/19,2023,7,Q3,2023-07-24,5,fashion,Lehenga,JIOMART,credit_card,1,7456.29,0.047,350.45,7456.29,"7,105.84",4505.10,2600.74,0.366,0,4.2,KARNATAKA,Mangalore,premium
3,ORD494773,CUST06352,30-Jan-2023,2023,1,Q1,03-Feb-2023,4,Sports & Fitness,Dumbbell Set,Amazon India,UPI,1,9372.67,21.0%,1968.26,9372.67,"7,404.41",5123.85,2280.56,0.308,0,3.7,Uttar Pradesh,Kanpur,Mid-Range
4,ORD261726,CUST03540,17-Dec-2023,2023,12,Q4,20/12/2023,3,Beauty & Personal Care,Hair Oil,Meesho,UPI,2,1762.47,4.4%,155.10,3524.94,"3,369.84",1644.48,1725.36,0.512,No,4.9,Maharashtra,Mumbai,mid-range
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48296,ORD736066,CUST02871,2022-04-30,2022,4,Q2,07/05/2022,7,SPORTS & FITNESS,Treadmill,Meesho,Wallet,1,9956.60,0.015,149.35,9956.60,9807.25,7561.39,2245.86,0.229,No,2.3,Madhya Pradesh,Gwalior,Budget
48297,ORD842538,CUST05548,23-Jul-2023,2023,7,Q3,26/07/2023,3,Sports & Fitness,Cricket Bat,Myntra,net_banking,3,12758.46,0.01,382.75,38275.38,"37,892.63",28343.69,9548.94,0.252,No,4.0,Maharashtra,Nashik,Mid-Range
48298,ORD755159,CUST01713,2022-03-26,2022,3,Q1,31/03/2022,5,home & kitchen,Bedsheet,meesho,CC,1,12431.38,14.9%,1852.28,12431.38,10579.10,7987.22,2591.88,0.245,0,2.8,Gujarat,Ahmedabad,Budget
48299,ORD568134,CUST05438,18-Jul-2023,2023,7,Q3,22-Jul-2023,4,Books & Stationery,ART SUPPLIES,amazon india,UPI,1,148.68,21.9%,32.56,148.68,116.12,68.74,47.38,0.408,Yes,3.0,Telangana,Karimnagar,Premium
48300,ORD292015,CUST04706,2023-01-15,2023,1,Q1,2023-01-19,4,Electronics,earbuds,Myntra,NetBanking,5,165563.33,2.5%,20695.42,827816.65,"807,121.23",727216.23,79905.00,0.099,0,2.1,tamil nadu,Coimbatore,Premium

In [5]:
date_fix = df[['order_date','delivery_date']]

for date in date_fix:
    df[date] = pd.to_datetime(df[date], format ='mixed')
    df[date] = df[date].dt.strftime('%d-%m-%Y')
df.head()

,order_id,customer_id,order_date,order_year,order_month,order_quarter,delivery_date,delivery_days,category,product,platform,payment_method,quantity,unit_price,discount_pct,discount_amount,gmv,revenue,cogs,profit,margin_pct,returned,rating,state,city,customer_segment
0,ORD658635,CUST03049,03-06-2023,2023,6,Q2,08-06-2023,5,Electronics,tablet,JioMart,UPI,2,56143.48,6.7%,7523.23,112286.96,"104,763.73",96277.87,8485.86,0.081,No,3.3,Tamil Nadu,chennai,mid-range
1,ORD766038,CUST04659,10-11-2023,2023,11,Q4,13-11-2023,3,Electronics,speaker,Amazon India,EMI,1,50953.37,29.6%,15082.20,50953.37,"35,871.17",32391.67,3479.50,0.097,0,4.5,DELHI,new delhi,Mid-Range
2,ORD419250,CUST02676,19-07-2023,2023,7,Q3,24-07-2023,5,fashion,Lehenga,JIOMART,credit_card,1,7456.29,0.047,350.45,7456.29,"7,105.84",4505.10,2600.74,0.366,0,4.2,KARNATAKA,Mangalore,premium
3,ORD494773,CUST06352,30-01-2023,2023,1,Q1,03-02-2023,4,Sports & Fitness,Dumbbell Set,Amazon India,UPI,1,9372.67,21.0%,1968.26,9372.67,"7,404.41",5123.85,2280.56,0.308,0,3.7,Uttar Pradesh,Kanpur,Mid-Range
4,ORD261726,CUST03540,17-12-2023,2023,12,Q4,20-12-2023,3,Beauty & Personal Care,Hair Oil,Meesho,UPI,2,1762.47,4.4%,155.10,3524.94,"3,369.84",1644.48,1725.36,0.512,No,4.9,Maharashtra,Mumbai,mid-range

In [6]:
text_col = df[['category','product','state','city','customer_segment']]

for col in text_col:
    df[col]=df[col].astype(str).str.strip().str.title()

df.head()

,order_id,customer_id,order_date,order_year,order_month,order_quarter,delivery_date,delivery_days,category,product,platform,payment_method,quantity,unit_price,discount_pct,discount_amount,gmv,revenue,cogs,profit,margin_pct,returned,rating,state,city,customer_segment
0,ORD658635,CUST03049,03-06-2023,2023,6,Q2,08-06-2023,5,Electronics,Tablet,JioMart,UPI,2,56143.48,6.7%,7523.23,112286.96,"104,763.73",96277.87,8485.86,0.081,No,3.3,Tamil Nadu,Chennai,Mid-Range
1,ORD766038,CUST04659,10-11-2023,2023,11,Q4,13-11-2023,3,Electronics,Speaker,Amazon India,EMI,1,50953.37,29.6%,15082.20,50953.37,"35,871.17",32391.67,3479.50,0.097,0,4.5,Delhi,New Delhi,Mid-Range
2,ORD419250,CUST02676,19-07-2023,2023,7,Q3,24-07-2023,5,Fashion,Lehenga,JIOMART,credit_card,1,7456.29,0.047,350.45,7456.29,"7,105.84",4505.10,2600.74,0.366,0,4.2,Karnataka,Mangalore,Premium
3,ORD494773,CUST06352,30-01-2023,2023,1,Q1,03-02-2023,4,Sports & Fitness,Dumbbell Set,Amazon India,UPI,1,9372.67,21.0%,1968.26,9372.67,"7,404.41",5123.85,2280.56,0.308,0,3.7,Uttar Pradesh,Kanpur,Mid-Range
4,ORD261726,CUST03540,17-12-2023,2023,12,Q4,20-12-2023,3,Beauty & Personal Care,Hair Oil,Meesho,UPI,2,1762.47,4.4%,155.10,3524.94,"3,369.84",1644.48,1725.36,0.512,No,4.9,Maharashtra,Mumbai,Mid-Range

In [7]:
df['platform'] = df['platform'].astype(str).str.strip().str.lower()
df.loc[df['platform'].str.contains('amazon'), 'platform'] = 'Amazon'
df.loc[df['platform'].str.contains('flipkart'), 'platform'] = 'Flipkart'
df['platform'] = df['platform'].str.title()
df.head()

,order_id,customer_id,order_date,order_year,order_month,order_quarter,delivery_date,delivery_days,category,product,platform,payment_method,quantity,unit_price,discount_pct,discount_amount,gmv,revenue,cogs,profit,margin_pct,returned,rating,state,city,customer_segment
0,ORD658635,CUST03049,03-06-2023,2023,6,Q2,08-06-2023,5,Electronics,Tablet,Jiomart,UPI,2,56143.48,6.7%,7523.23,112286.96,"104,763.73",96277.87,8485.86,0.081,No,3.3,Tamil Nadu,Chennai,Mid-Range
1,ORD766038,CUST04659,10-11-2023,2023,11,Q4,13-11-2023,3,Electronics,Speaker,Amazon,EMI,1,50953.37,29.6%,15082.20,50953.37,"35,871.17",32391.67,3479.50,0.097,0,4.5,Delhi,New Delhi,Mid-Range
2,ORD419250,CUST02676,19-07-2023,2023,7,Q3,24-07-2023,5,Fashion,Lehenga,Jiomart,credit_card,1,7456.29,0.047,350.45,7456.29,"7,105.84",4505.10,2600.74,0.366,0,4.2,Karnataka,Mangalore,Premium
3,ORD494773,CUST06352,30-01-2023,2023,1,Q1,03-02-2023,4,Sports & Fitness,Dumbbell Set,Amazon,UPI,1,9372.67,21.0%,1968.26,9372.67,"7,404.41",5123.85,2280.56,0.308,0,3.7,Uttar Pradesh,Kanpur,Mid-Range
4,ORD261726,CUST03540,17-12-2023,2023,12,Q4,20-12-2023,3,Beauty & Personal Care,Hair Oil,Meesho,UPI,2,1762.47,4.4%,155.10,3524.94,"3,369.84",1644.48,1725.36,0.512,No,4.9,Maharashtra,Mumbai,Mid-Range

In [8]:
df['payment_method'] = df['payment_method'].astype(str).str.strip().str.lower()

pay_map ={
    'cash on delivery' : 'Cash On Delivery','debit card' : 'Debit Card','emi' : 'EMI','wallet' : 'Wallet','upi' :'UPI',
    'cc' : 'Credit Card','credit_card' : 'Credit Card' , 'credit card' : 'Credit Card',
    'net banking' : 'Net Banking','net_banking' : 'Net Banking','netbanking' : 'Net Banking'
}
df['payment_method'] = df['payment_method'].map(pay_map)
df.head()

,order_id,customer_id,order_date,order_year,order_month,order_quarter,delivery_date,delivery_days,category,product,platform,payment_method,quantity,unit_price,discount_pct,discount_amount,gmv,revenue,cogs,profit,margin_pct,returned,rating,state,city,customer_segment
0,ORD658635,CUST03049,03-06-2023,2023,6,Q2,08-06-2023,5,Electronics,Tablet,Jiomart,UPI,2,56143.48,6.7%,7523.23,112286.96,"104,763.73",96277.87,8485.86,0.081,No,3.3,Tamil Nadu,Chennai,Mid-Range
1,ORD766038,CUST04659,10-11-2023,2023,11,Q4,13-11-2023,3,Electronics,Speaker,Amazon,EMI,1,50953.37,29.6%,15082.20,50953.37,"35,871.17",32391.67,3479.50,0.097,0,4.5,Delhi,New Delhi,Mid-Range
2,ORD419250,CUST02676,19-07-2023,2023,7,Q3,24-07-2023,5,Fashion,Lehenga,Jiomart,Credit Card,1,7456.29,0.047,350.45,7456.29,"7,105.84",4505.10,2600.74,0.366,0,4.2,Karnataka,Mangalore,Premium
3,ORD494773,CUST06352,30-01-2023,2023,1,Q1,03-02-2023,4,Sports & Fitness,Dumbbell Set,Amazon,UPI,1,9372.67,21.0%,1968.26,9372.67,"7,404.41",5123.85,2280.56,0.308,0,3.7,Uttar Pradesh,Kanpur,Mid-Range
4,ORD261726,CUST03540,17-12-2023,2023,12,Q4,20-12-2023,3,Beauty & Personal Care,Hair Oil,Meesho,UPI,2,1762.47,4.4%,155.10,3524.94,"3,369.84",1644.48,1725.36,0.512,No,4.9,Maharashtra,Mumbai,Mid-Range

In [9]:
df['revenue'] = df['revenue'].astype(str).str.replace(',','', regex = False).str.strip()
df['revenue'] = pd.to_numeric(df['revenue'])
df.head()

,order_id,customer_id,order_date,order_year,order_month,order_quarter,delivery_date,delivery_days,category,product,platform,payment_method,quantity,unit_price,discount_pct,discount_amount,gmv,revenue,cogs,profit,margin_pct,returned,rating,state,city,customer_segment
0,ORD658635,CUST03049,03-06-2023,2023,6,Q2,08-06-2023,5,Electronics,Tablet,Jiomart,UPI,2,56143.48,6.7%,7523.23,112286.96,104763.73,96277.87,8485.86,0.081,No,3.3,Tamil Nadu,Chennai,Mid-Range
1,ORD766038,CUST04659,10-11-2023,2023,11,Q4,13-11-2023,3,Electronics,Speaker,Amazon,EMI,1,50953.37,29.6%,15082.20,50953.37,35871.17,32391.67,3479.50,0.097,0,4.5,Delhi,New Delhi,Mid-Range
2,ORD419250,CUST02676,19-07-2023,2023,7,Q3,24-07-2023,5,Fashion,Lehenga,Jiomart,Credit Card,1,7456.29,0.047,350.45,7456.29,7105.84,4505.10,2600.74,0.366,0,4.2,Karnataka,Mangalore,Premium
3,ORD494773,CUST06352,30-01-2023,2023,1,Q1,03-02-2023,4,Sports & Fitness,Dumbbell Set,Amazon,UPI,1,9372.67,21.0%,1968.26,9372.67,7404.41,5123.85,2280.56,0.308,0,3.7,Uttar Pradesh,Kanpur,Mid-Range
4,ORD261726,CUST03540,17-12-2023,2023,12,Q4,20-12-2023,3,Beauty & Personal Care,Hair Oil,Meesho,UPI,2,1762.47,4.4%,155.10,3524.94,3369.84,1644.48,1725.36,0.512,No,4.9,Maharashtra,Mumbai,Mid-Range

In [10]:
def dic_fix(value):

    if '%' in value:
        value = str(value).strip()
        return float(value.replace('%',''))/100
    return float(value)

df['discount_pct'] = df['discount_pct'].apply(dic_fix)

df.head()

,order_id,customer_id,order_date,order_year,order_month,order_quarter,delivery_date,delivery_days,category,product,platform,payment_method,quantity,unit_price,discount_pct,discount_amount,gmv,revenue,cogs,profit,margin_pct,returned,rating,state,city,customer_segment
0,ORD658635,CUST03049,03-06-2023,2023,6,Q2,08-06-2023,5,Electronics,Tablet,Jiomart,UPI,2,56143.48,0.067,7523.23,112286.96,104763.73,96277.87,8485.86,0.081,No,3.3,Tamil Nadu,Chennai,Mid-Range
1,ORD766038,CUST04659,10-11-2023,2023,11,Q4,13-11-2023,3,Electronics,Speaker,Amazon,EMI,1,50953.37,0.296,15082.20,50953.37,35871.17,32391.67,3479.50,0.097,0,4.5,Delhi,New Delhi,Mid-Range
2,ORD419250,CUST02676,19-07-2023,2023,7,Q3,24-07-2023,5,Fashion,Lehenga,Jiomart,Credit Card,1,7456.29,0.047,350.45,7456.29,7105.84,4505.10,2600.74,0.366,0,4.2,Karnataka,Mangalore,Premium
3,ORD494773,CUST06352,30-01-2023,2023,1,Q1,03-02-2023,4,Sports & Fitness,Dumbbell Set,Amazon,UPI,1,9372.67,0.210,1968.26,9372.67,7404.41,5123.85,2280.56,0.308,0,3.7,Uttar Pradesh,Kanpur,Mid-Range
4,ORD261726,CUST03540,17-12-2023,2023,12,Q4,20-12-2023,3,Beauty & Personal Care,Hair Oil,Meesho,UPI,2,1762.47,0.044,155.10,3524.94,3369.84,1644.48,1725.36,0.512,No,4.9,Maharashtra,Mumbai,Mid-Range

In [11]:
df['returned'] = df['returned'].astype(str).str.strip().str.lower()
ret_map = {'1' : 1, '0' :0,'yes' : 1, 'no' :0}
df['returned'] = df['returned'].map(ret_map).fillna(0).astype(int)

df

,order_id,customer_id,order_date,order_year,order_month,order_quarter,delivery_date,delivery_days,category,product,platform,payment_method,quantity,unit_price,discount_pct,discount_amount,gmv,revenue,cogs,profit,margin_pct,returned,rating,state,city,customer_segment
0,ORD658635,CUST03049,03-06-2023,2023,6,Q2,08-06-2023,5,Electronics,Tablet,Jiomart,UPI,2,56143.48,0.067,7523.23,112286.96,104763.73,96277.87,8485.86,0.081,0,3.3,Tamil Nadu,Chennai,Mid-Range
1,ORD766038,CUST04659,10-11-2023,2023,11,Q4,13-11-2023,3,Electronics,Speaker,Amazon,EMI,1,50953.37,0.296,15082.20,50953.37,35871.17,32391.67,3479.50,0.097,0,4.5,Delhi,New Delhi,Mid-Range
2,ORD419250,CUST02676,19-07-2023,2023,7,Q3,24-07-2023,5,Fashion,Lehenga,Jiomart,Credit Card,1,7456.29,0.047,350.45,7456.29,7105.84,4505.10,2600.74,0.366,0,4.2,Karnataka,Mangalore,Premium
3,ORD494773,CUST06352,30-01-2023,2023,1,Q1,03-02-2023,4,Sports & Fitness,Dumbbell Set,Amazon,UPI,1,9372.67,0.210,1968.26,9372.67,7404.41,5123.85,2280.56,0.308,0,3.7,Uttar Pradesh,Kanpur,Mid-Range
4,ORD261726,CUST03540,17-12-2023,2023,12,Q4,20-12-2023,3,Beauty & Personal Care,Hair Oil,Meesho,UPI,2,1762.47,0.044,155.10,3524.94,3369.84,1644.48,1725.36,0.512,0,4.9,Maharashtra,Mumbai,Mid-Range
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48296,ORD736066,CUST02871,30-04-2022,2022,4,Q2,05-07-2022,7,Sports & Fitness,Treadmill,Meesho,Wallet,1,9956.60,0.015,149.35,9956.60,9807.25,7561.39,2245.86,0.229,0,2.3,Madhya Pradesh,Gwalior,Budget
48297,ORD842538,CUST05548,23-07-2023,2023,7,Q3,26-07-2023,3,Sports & Fitness,Cricket Bat,Myntra,Net Banking,3,12758.46,0.010,382.75,38275.38,37892.63,28343.69,9548.94,0.252,0,4.0,Maharashtra,Nashik,Mid-Range
48298,ORD755159,CUST01713,26-03-2022,2022,3,Q1,31-03-2022,5,Home & Kitchen,Bedsheet,Meesho,Credit Card,1,12431.38,0.149,1852.28,12431.38,10579.10,7987.22,2591.88,0.245,0,2.8,Gujarat,Ahmedabad,Budget
48299,ORD568134,CUST05438,18-07-2023,2023,7,Q3,22-07-2023,4,Books & Stationery,Art Supplies,Amazon,UPI,1,148.68,0.219,32.56,148.68,116.12,68.74,47.38,0.408,1,3.0,Telangana,Karimnagar,Premium
48300,ORD292015,CUST04706,15-01-2023,2023,1,Q1,19-01-2023,4,Electronics,Earbuds,Myntra,Net Banking,5,165563.33,0.025,20695.42,827816.65,807121.23,727216.23,79905.00,0.099,0,2.1,Tamil Nadu,Coimbatore,Premium

In [12]:
from sqlalchemy import create_engine


username = "root"
password = "1234"
host = "localhost"
port = "3306"
database = "india_ecomm_sales"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

table_name = "orders" 
df.to_sql(table_name, engine, if_exists="replace", index=False)

pd.read_sql("SELECT * FROM customer LIMIT 5;", engine)

,customer_id,name,age,gender,state,city,segment,registration_date
0,CUST05109,Diya Nair,45,Male,Gujarat,Gandhinagar,Luxury,07-02-2020
1,CUST00782,Kabir Menon,39,Female,Uttar Pradesh,Agra,Premium,02-08-2021
2,CUST01577,Lakshmi Sharma,45,Female,Maharashtra,Pune,Mid-Range,20-12-2020
3,CUST04580,Sanjay Singh,59,Female,West Bengal,Kolkata,Budget,15-09-2021
4,CUST04492,Aditya Mehta,59,Male,Rajasthan,Jaipur,Budget,22-06-2020